@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package io.github.gaming32.signaturechanger;

import io.github.gaming32.signaturechanger.annotation.FieldsAreNonnullByDefault;
import io.github.gaming32.signaturechanger.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
